# Compiling program in Haskell is similar to compiling it in C
# And by similarity i mean that Haskell also compiles code to
# binary file and moreover the syntax (how You write this command)
# stays the same

compile:
	ghc ex2.hs -o ex2.out

run:
	./ex2.out

delete:
	rm *.out *.hi *.o
